import type {
  User,
  Property,
  SocialPost,
  Conversation,
  Reservation,
  Referral,
  Formation,
  Event,
  Notification,
  DashboardStats,
  Transaction,
  MonthlyRevenue,
  MonthlyReferralEarnings,
  PaidOption,
} from "./types";

// ─── Users ───────────────────────────────────────────────

export const currentUser: User = {
  id: "u1",
  firstName: "Karim",
  lastName: "Benali",
  email: "karim.benali@edome.ch",
  avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
  roles: ["hote", "apporteur"],
  activeRole: "hote",
  phone: "+41 79 123 45 67",
  country: "Suisse",
  city: "Neuchâtel",
  bio: "Passionné d'immobilier, hôte expérimenté en Suisse romande. Spécialisé dans les locations courte durée et l'investissement locatif.",
  verified: true,
  kycLevel: 3,
  stats: {
    followers: 1243,
    following: 387,
    properties: 12,
    rating: 4.8,
    reviewCount: 156,
  },
  joinedAt: "2024-03-15",
  online: true,
  languages: ['Fran\u00e7ais', 'English', '\u0627\u0644\u0639\u0631\u0628\u064a\u0629'],
  certifications: [
    { title: 'Agent Immobilier Certifi\u00e9', issuer: 'Chambre Immobili\u00e8re Suisse', date: '2024-06' },
    { title: 'Expert Investissement Locatif', issuer: 'E-Dome Academy', date: '2025-01' },
  ],
  responseTime: 2,
};

export const users: User[] = [
  currentUser,
  {
    id: "u2",
    firstName: "Sophie",
    lastName: "Martin",
    email: "sophie.martin@gmail.com",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
    roles: ["client"],
    activeRole: "client",
    phone: "+41 78 234 56 78",
    country: "Suisse",
    city: "Lausanne",
    bio: "Recherche un appartement à louer en Suisse romande.",
    verified: true,
    kycLevel: 2,
    stats: { followers: 234, following: 189, properties: 0, rating: 4.5, reviewCount: 12 },
    joinedAt: "2024-06-10",
    online: true,
  },
  {
    id: "u3",
    firstName: "Marc",
    lastName: "Dupont",
    email: "marc.dupont@immo.ch",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    roles: ["proprietaire", "investisseur"],
    activeRole: "proprietaire",
    phone: "+41 76 345 67 89",
    country: "Suisse",
    city: "Genève",
    bio: "Investisseur immobilier avec un portefeuille de 30+ biens en Suisse et en France.",
    verified: true,
    kycLevel: 3,
    stats: { followers: 3420, following: 156, properties: 32, rating: 4.9, reviewCount: 287 },
    joinedAt: "2023-11-20",
    online: false,
  },
  {
    id: "u4",
    firstName: "Amina",
    lastName: "El Fassi",
    email: "amina.elfassi@agence.ma",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    roles: ["agence"],
    activeRole: "agence",
    phone: "+212 6 12 34 56 78",
    country: "Maroc",
    city: "Marrakech",
    bio: "Directrice d'agence immobilière spécialisée dans le luxe à Marrakech et Casablanca.",
    verified: true,
    kycLevel: 3,
    stats: { followers: 5670, following: 432, properties: 45, rating: 4.7, reviewCount: 312 },
    joinedAt: "2024-01-08",
    online: true,
  },
  {
    id: "u5",
    firstName: "Luca",
    lastName: "Ferreira",
    email: "luca.ferreira@email.pt",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    roles: ["hote"],
    activeRole: "hote",
    phone: "+351 91 234 56 78",
    country: "Portugal",
    city: "Lisbonne",
    bio: "Hôte Superhost, propriétaire de 8 biens entre Lisbonne et l'Algarve.",
    verified: true,
    kycLevel: 2,
    stats: { followers: 1890, following: 245, properties: 8, rating: 4.9, reviewCount: 203 },
    joinedAt: "2024-02-14",
    online: false,
  },
  {
    id: "u6",
    firstName: "Chloé",
    lastName: "Roux",
    email: "chloe.roux@email.fr",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
    roles: ["apporteur"],
    activeRole: "apporteur",
    phone: "+33 6 12 34 56 78",
    country: "France",
    city: "Lyon",
    bio: "Apporteuse d'affaires spécialisée en immobilier résidentiel et commercial.",
    verified: true,
    kycLevel: 2,
    stats: { followers: 876, following: 534, properties: 0, rating: 4.6, reviewCount: 67 },
    joinedAt: "2024-04-22",
    online: true,
  },
  {
    id: "u7",
    firstName: "Omar",
    lastName: "Tazi",
    email: "omar.tazi@invest.ma",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    roles: ["investisseur", "promoteur"],
    activeRole: "investisseur",
    phone: "+212 6 98 76 54 32",
    country: "Maroc",
    city: "Casablanca",
    bio: "Investisseur et promoteur immobilier, projets de développement au Maroc et à Dubaï.",
    verified: true,
    kycLevel: 3,
    stats: { followers: 4230, following: 198, properties: 18, rating: 4.8, reviewCount: 145 },
    joinedAt: "2023-09-05",
    online: false,
  },
  {
    id: "u8",
    firstName: "Elena",
    lastName: "Papadopoulos",
    email: "elena.papa@email.gr",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
    roles: ["hote", "proprietaire"],
    activeRole: "hote",
    phone: "+30 69 12 34 56 78",
    country: "Grèce",
    city: "Athènes",
    bio: "Propriétaire de villas de luxe dans les Cyclades. Passionnée d'hospitalité méditerranéenne.",
    verified: true,
    kycLevel: 2,
    stats: { followers: 2340, following: 312, properties: 6, rating: 4.9, reviewCount: 178 },
    joinedAt: "2024-05-01",
    online: true,
  },
  {
    id: "u9",
    firstName: "Thomas",
    lastName: "Müller",
    email: "thomas.muller@formation.ch",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face",
    roles: ["formateur"],
    activeRole: "formateur",
    phone: "+41 79 456 78 90",
    country: "Suisse",
    city: "Zurich",
    bio: "Expert en investissement immobilier. 15 ans d'expérience, formateur certifié.",
    verified: true,
    kycLevel: 3,
    stats: { followers: 8900, following: 67, properties: 5, rating: 4.9, reviewCount: 432 },
    joinedAt: "2023-06-15",
    online: false,
  },
  {
    id: "u10",
    firstName: "Yasmine",
    lastName: "Bouchard",
    email: "yasmine.b@email.ch",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&h=150&fit=crop&crop=face",
    roles: ["client", "apporteur"],
    activeRole: "client",
    phone: "+41 77 567 89 01",
    country: "Suisse",
    city: "Fribourg",
    bio: "À la recherche de mon premier investissement immobilier en Suisse romande.",
    verified: true,
    kycLevel: 1,
    stats: { followers: 156, following: 432, properties: 0, rating: 0, reviewCount: 0 },
    joinedAt: "2025-01-10",
    online: true,
  },
  {
    id: "u11",
    firstName: "Pierre",
    lastName: "Lecomte",
    email: "pierre.lecomte@promo.fr",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    roles: ["promoteur"],
    activeRole: "promoteur",
    phone: "+33 6 78 90 12 34",
    country: "France",
    city: "Paris",
    bio: "Promoteur immobilier, projets neufs en Île-de-France et sur la Côte d'Azur.",
    verified: true,
    kycLevel: 3,
    stats: { followers: 6780, following: 89, properties: 24, rating: 4.7, reviewCount: 198 },
    joinedAt: "2023-12-01",
    online: false,
  },
  {
    id: "u12",
    firstName: "Fatima",
    lastName: "Alaoui",
    email: "fatima.alaoui@email.ma",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&h=150&fit=crop&crop=face",
    roles: ["hote"],
    activeRole: "hote",
    phone: "+212 6 34 56 78 90",
    country: "Maroc",
    city: "Tanger",
    bio: "Hôte à Tanger, spécialisée dans les riads traditionnels rénovés.",
    verified: true,
    kycLevel: 2,
    stats: { followers: 987, following: 234, properties: 4, rating: 4.8, reviewCount: 89 },
    joinedAt: "2024-07-20",
    online: true,
  },
  {
    id: "u13",
    firstName: "João",
    lastName: "Silva",
    email: "joao.silva@email.pt",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    roles: ["agence", "hote"],
    activeRole: "agence",
    phone: "+351 92 345 67 89",
    country: "Portugal",
    city: "Porto",
    bio: "Agence immobilière au nord du Portugal. Résidentiel et investissement.",
    verified: true,
    kycLevel: 3,
    stats: { followers: 3450, following: 178, properties: 38, rating: 4.6, reviewCount: 267 },
    joinedAt: "2024-03-01",
    online: false,
  },
  {
    id: "u14",
    firstName: "Nadia",
    lastName: "Berset",
    email: "nadia.berset@email.ch",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
    roles: ["admin"],
    activeRole: "admin",
    phone: "+41 79 678 90 12",
    country: "Suisse",
    city: "Berne",
    bio: "Administratrice de la plateforme E-Dome.",
    verified: true,
    kycLevel: 3,
    stats: { followers: 450, following: 120, properties: 0, rating: 0, reviewCount: 0 },
    joinedAt: "2023-01-01",
    online: true,
  },
  {
    id: "u15",
    firstName: "Ahmed",
    lastName: "Khalil",
    email: "ahmed.khalil@email.ae",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    roles: ["investisseur", "promoteur"],
    activeRole: "investisseur",
    phone: "+971 50 123 4567",
    country: "Émirats arabes unis",
    city: "Dubaï",
    bio: "Investisseur immobilier international, spécialisé dans les projets premium à Dubaï et en Europe.",
    verified: true,
    kycLevel: 3,
    stats: { followers: 12400, following: 56, properties: 15, rating: 4.9, reviewCount: 98 },
    joinedAt: "2024-08-15",
    online: false,
  },
  {
    id: "u16",
    firstName: "Isabelle",
    lastName: "Moreira",
    email: "isabelle.moreira@email.ch",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    roles: ["client", "hote"],
    activeRole: "hote",
    phone: "+41 78 789 01 23",
    country: "Suisse",
    city: "Montreux",
    bio: "Propriétaire de deux chalets dans les Alpes vaudoises. Accueil personnalisé.",
    verified: true,
    kycLevel: 2,
    stats: { followers: 567, following: 290, properties: 2, rating: 4.7, reviewCount: 45 },
    joinedAt: "2024-09-01",
    online: true,
  },
];

// ─── Paid Options ────────────────────────────────────────

const paidOptionsSets: Record<string, PaidOption[]> = {
  standard: [
    { id: "po1", name: "Ménage fin de séjour", description: "Nettoyage complet de l'appartement à la fin du séjour", price: 150 },
    { id: "po2", name: "Parking privé", description: "Place de parking sécurisée dans le garage souterrain", price: 20, perDay: true },
    { id: "po3", name: "Petit-déjeuner", description: "Petit-déjeuner continental livré chaque matin", price: 15, perDay: true },
    { id: "po4", name: "Navette aéroport", description: "Transfert aller-retour depuis l'aéroport", price: 80 },
  ],
  premium: [
    { id: "po5", name: "Ménage fin de séjour", description: "Nettoyage complet professionnel", price: 200 },
    { id: "po6", name: "Parking privé", description: "Place de parking dans le garage privé", price: 30, perDay: true },
    { id: "po7", name: "Petit-déjeuner", description: "Petit-déjeuner gastronomique livré chaque matin", price: 25, perDay: true },
    { id: "po8", name: "Navette aéroport", description: "Transfert en véhicule premium depuis l'aéroport", price: 120 },
    { id: "po9", name: "Linge de maison premium", description: "Draps et serviettes de luxe en coton égyptien", price: 50 },
    { id: "po10", name: "Accès spa & wellness", description: "Accès illimité à l'espace bien-être de la résidence", price: 40, perDay: true },
  ],
  chalet: [
    { id: "po11", name: "Ménage fin de séjour", description: "Nettoyage complet du chalet", price: 250 },
    { id: "po12", name: "Forfait ski", description: "Forfait ski journalier pour la station", price: 65, perDay: true },
    { id: "po13", name: "Raclette / Fondue", description: "Kit raclette ou fondue avec fromages locaux", price: 45 },
    { id: "po14", name: "Bois de cheminée", description: "Provision de bois pour la cheminée", price: 30 },
    { id: "po15", name: "Navette station", description: "Transfert depuis la gare la plus proche", price: 60 },
  ],
};

// ─── Properties ──────────────────────────────────────────

export const properties: Property[] = [
  {
    id: "p1",
    title: "Appartement moderne avec vue sur le lac",
    description: "Superbe appartement de 3.5 pièces entièrement rénové avec une vue imprenable sur le lac de Neuchâtel. Cuisine équipée, balcon spacieux, parking souterrain. Idéal pour un séjour romantique ou professionnel.",
    type: "appartement",
    transactionType: "location-ct",
    price: 2200,
    currency: "CHF",
    pricePerNight: 185,
    location: { address: "Rue du Seyon 12", city: "Neuchâtel", country: "Suisse", lat: 46.992, lng: 6.9311 },
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&h=600&fit=crop"],
    videos: [],
    bedrooms: 2,
    bathrooms: 1,
    area: 85,
    floor: 4,
    equipment: ["WiFi", "Cuisine équipée", "Lave-linge", "Balcon", "Parking", "TV connectée", "Climatisation"],
    host: currentUser,
    rating: 4.8,
    reviewCount: 42,
    views: 1230,
    createdAt: "2025-01-15",
    status: "active",
    featured: true,
    paidOptions: paidOptionsSets.standard,
    availabilities: [{ start: "2026-04-01", end: "2026-06-30" }, { start: "2026-08-01", end: "2026-12-31" }],
  },
  {
    id: "p2",
    title: "Villa de luxe avec piscine à Marrakech",
    description: "Magnifique villa de 5 chambres avec piscine privée, jardin tropical et personnel de maison. Située dans le quartier prisé de la Palmeraie, à 15 minutes du centre-ville.",
    type: "villa",
    transactionType: "location-ct",
    price: 3500,
    currency: "EUR",
    pricePerNight: 450,
    location: { address: "Route de la Palmeraie, Km 8", city: "Marrakech", country: "Maroc", lat: 31.6695, lng: -7.9811 },
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a6?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1539437829697-1b4ed5aebd19?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1548018560-c7196bddcbec?w=800&h=600&fit=crop"],
    videos: ["/videos/property-tour-1.mp4"],
    bedrooms: 5,
    bathrooms: 4,
    area: 350,
    equipment: ["Piscine privée", "Jardin", "WiFi", "Climatisation", "Personnel de maison", "BBQ", "Salle de sport", "Hammam"],
    host: users[3],
    rating: 4.9,
    reviewCount: 87,
    views: 4560,
    createdAt: "2024-11-20",
    status: "active",
    featured: true,
    paidOptions: paidOptionsSets.premium,
  },
  {
    id: "p3",
    title: "Penthouse panoramique à Genève",
    description: "Exceptionnel penthouse de 200m² avec terrasse de 60m² offrant une vue à 360° sur le Jet d'eau, le lac Léman et le Mont-Blanc. Finitions haut de gamme, domotique complète.",
    type: "penthouse",
    transactionType: "vente",
    price: 4500000,
    currency: "CHF",
    location: { address: "Quai du Mont-Blanc 33", city: "Genève", country: "Suisse", lat: 46.209, lng: 6.1518 },
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c0?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a6?w=800&h=600&fit=crop"],
    videos: ["/videos/property-tour-1.mp4"],
    bedrooms: 4,
    bathrooms: 3,
    area: 200,
    floor: 12,
    equipment: ["Terrasse panoramique", "Domotique", "Cave à vin", "Garage double", "Concierge 24h", "Spa privatif"],
    host: users[2],
    rating: 5.0,
    reviewCount: 3,
    views: 8920,
    createdAt: "2025-02-01",
    status: "active",
    featured: true,
    paidOptions: [],
    analytics: {
      rendementBrut: 3.2,
      rendementNet: 2.1,
      prixM2: Math.round(4500000 / 200),
      dpe: "A",
      etatGeneral: "Neuf",
      anneeConstruction: 2023,
      potentielPlusValue: "Moyen",
      roi5ans: 18,
      roi10ans: 42,
    },
  },
  {
    id: "p4",
    title: "Chalet traditionnel à Verbier",
    description: "Authentique chalet suisse en bois avec cheminée, sauna et vue imprenable sur les Alpes. À 200m des remontées mécaniques. Parfait pour les amateurs de ski et de nature.",
    type: "chalet",
    transactionType: "location-ct",
    price: 4800,
    currency: "CHF",
    pricePerNight: 380,
    location: { address: "Route de Verbier 45", city: "Verbier", country: "Suisse", lat: 46.0967, lng: 7.2292 },
    images: ["https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop"],
    videos: ["/videos/property-tour-2.mp4"],
    bedrooms: 4,
    bathrooms: 3,
    area: 180,
    equipment: ["Cheminée", "Sauna", "WiFi", "Garage", "Terrasse", "Vue montagnes", "Ski-in/Ski-out"],
    host: users[15],
    rating: 4.9,
    reviewCount: 67,
    views: 3450,
    createdAt: "2024-10-05",
    status: "active",
    featured: true,
    paidOptions: paidOptionsSets.chalet,
  },
  {
    id: "p5",
    title: "Loft industriel au cœur de Lyon",
    description: "Superbe loft de 120m² dans une ancienne usine textile réhabilitée. Plafonds de 4m, grandes baies vitrées, cuisine ouverte design. Quartier Confluence.",
    type: "loft",
    transactionType: "location-lt",
    price: 1800,
    currency: "EUR",
    location: { address: "Rue Casimir Périer 18", city: "Lyon", country: "France", lat: 45.7484, lng: 4.8191 },
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop"],
    videos: [],
    bedrooms: 2,
    bathrooms: 1,
    area: 120,
    floor: 2,
    equipment: ["WiFi fibre", "Cuisine design", "Lave-vaisselle", "Buanderie", "Cave", "Vélos fournis"],
    host: users[5],
    rating: 4.6,
    reviewCount: 23,
    views: 1890,
    createdAt: "2025-03-01",
    status: "active",
    featured: false,
    paidOptions: [],
  },
  {
    id: "p6",
    title: "Appartement T3 avec terrasse à Lisbonne",
    description: "Charmant appartement de 3 pièces dans le quartier historique de l'Alfama. Terrasse avec vue sur le Tage, entièrement meublé et équipé. Proche de tous les transports.",
    type: "appartement",
    transactionType: "location-ct",
    price: 1400,
    currency: "EUR",
    pricePerNight: 120,
    location: { address: "Rua da Saudade 42", city: "Lisbonne", country: "Portugal", lat: 38.7106, lng: -9.1307 },
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop"],
    videos: ["/videos/property-tour-1.mp4"],
    bedrooms: 2,
    bathrooms: 1,
    area: 75,
    floor: 3,
    equipment: ["WiFi", "Terrasse", "Climatisation", "Machine à laver", "Cuisine équipée", "Vue Tage"],
    host: users[4],
    rating: 4.7,
    reviewCount: 56,
    views: 2340,
    createdAt: "2024-12-10",
    status: "active",
    featured: false,
    paidOptions: paidOptionsSets.standard,
  },
  {
    id: "p7",
    title: "Villa contemporaine à Dubaï Marina",
    description: "Spectaculaire villa de 6 chambres à Dubaï Marina avec vue sur la mer et la skyline. Piscine à débordement, cinéma privé, garage 4 voitures. Le summum du luxe.",
    type: "villa",
    transactionType: "vente",
    price: 8500000,
    currency: "EUR",
    location: { address: "Marina Walk, Tower 5", city: "Dubaï", country: "Émirats arabes unis", lat: 25.0805, lng: 55.1403 },
    images: ["https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1582672060674-bc2bd808a8b5?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a6?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop"],
    videos: ["/videos/property-tour-2.mp4"],
    bedrooms: 6,
    bathrooms: 7,
    area: 520,
    equipment: ["Piscine à débordement", "Cinéma privé", "Salle de sport", "Spa", "Garage 4 voitures", "Personnel", "Smart home", "Plage privée"],
    host: users[14],
    rating: 5.0,
    reviewCount: 12,
    views: 15600,
    createdAt: "2025-01-25",
    status: "active",
    featured: true,
    paidOptions: [],
    analytics: {
      rendementBrut: 4.5,
      rendementNet: 3.1,
      prixM2: Math.round(8500000 / 520),
      dpe: "A",
      etatGeneral: "Neuf",
      anneeConstruction: 2024,
      potentielPlusValue: "Tres eleve",
      roi5ans: 35,
      roi10ans: 78,
    },
  },
  {
    id: "p8",
    title: "Studio meublé au centre de Lausanne",
    description: "Studio fonctionnel de 32m² idéalement situé près de la gare de Lausanne. Parfait pour étudiants ou professionnels. Entièrement meublé et équipé.",
    type: "studio",
    transactionType: "location-lt",
    price: 1350,
    currency: "CHF",
    location: { address: "Avenue de la Gare 8", city: "Lausanne", country: "Suisse", lat: 46.5197, lng: 6.6323 },
    images: ["https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1494526585095-c41746248156?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop"],
    videos: [],
    bedrooms: 1,
    bathrooms: 1,
    area: 32,
    floor: 2,
    equipment: ["WiFi", "Cuisine équipée", "Lave-linge commun", "Cave", "Proche transports"],
    host: currentUser,
    rating: 4.4,
    reviewCount: 18,
    views: 890,
    createdAt: "2025-02-20",
    status: "active",
    featured: false,
    paidOptions: [],
  },
  {
    id: "p9",
    title: "Riad authentique dans la Médina de Fès",
    description: "Riad traditionnel entièrement restauré au cœur de la médina de Fès. 4 chambres autour d'un patio avec fontaine, terrasse avec vue sur la ville. Authenticité et confort moderne.",
    type: "maison",
    transactionType: "location-ct",
    price: 2000,
    currency: "EUR",
    pricePerNight: 160,
    location: { address: "Derb Sidi Ahmed 7, Médina", city: "Fès", country: "Maroc", lat: 34.0628, lng: -4.9737 },
    images: ["https://images.unsplash.com/photo-1539437829697-1b4ed5aebd19?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1548018560-c7196bddcbec?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop"],
    videos: [],
    bedrooms: 4,
    bathrooms: 4,
    area: 200,
    equipment: ["Patio", "Fontaine", "Terrasse", "WiFi", "Climatisation", "Hammam traditionnel", "Cuisine marocaine"],
    host: users[11],
    rating: 4.8,
    reviewCount: 94,
    views: 3780,
    createdAt: "2024-09-15",
    status: "active",
    featured: true,
    paidOptions: paidOptionsSets.premium,
  },
  {
    id: "p10",
    title: "Terrain constructible vue mer en Grèce",
    description: "Terrain de 2'500m² avec permis de construire, vue panoramique sur la mer Égée. Situé sur l'île de Paros dans les Cyclades. Opportunité rare.",
    type: "terrain",
    transactionType: "vente",
    price: 680000,
    currency: "EUR",
    location: { address: "Naoussa Heights", city: "Paros", country: "Grèce", lat: 37.1233, lng: 25.2356 },
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop"],
    videos: [],
    bedrooms: 0,
    bathrooms: 0,
    area: 2500,
    equipment: ["Vue mer", "Permis de construire", "Accès route", "Eau & électricité", "Proche plage"],
    host: users[7],
    rating: 0,
    reviewCount: 0,
    views: 5670,
    createdAt: "2025-03-10",
    status: "active",
    featured: false,
    paidOptions: [],
    analytics: {
      rendementBrut: 5.8,
      rendementNet: 4.2,
      prixM2: Math.round(680000 / 2500),
      dpe: "B",
      etatGeneral: "Bon",
      potentielPlusValue: "Tres eleve",
      roi5ans: 32,
      roi10ans: 70,
    },
  },
  {
    id: "p11",
    title: "Appartement neuf à Nyon avec vue lac",
    description: "Magnifique 4.5 pièces dans une résidence neuve à Nyon. Vue dégagée sur le lac Léman et les Alpes. Finitions premium, cuisine Bulthaup, domotique intégrée.",
    type: "appartement",
    transactionType: "vente",
    price: 1250000,
    currency: "CHF",
    location: { address: "Route de Genève 54", city: "Nyon", country: "Suisse", lat: 46.3833, lng: 6.2396 },
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1494526585095-c41746248156?w=800&h=600&fit=crop"],
    videos: [],
    bedrooms: 3,
    bathrooms: 2,
    area: 110,
    floor: 5,
    equipment: ["Vue lac", "Domotique", "Cuisine Bulthaup", "2 balcons", "Garage", "Cave", "Buanderie privée"],
    host: users[2],
    rating: 0,
    reviewCount: 0,
    views: 2340,
    createdAt: "2025-03-15",
    status: "active",
    featured: true,
    paidOptions: [],
    analytics: {
      rendementBrut: 4.2,
      rendementNet: 2.9,
      prixM2: Math.round(1250000 / 110),
      dpe: "A",
      etatGeneral: "Neuf",
      anneeConstruction: 2025,
      potentielPlusValue: "Eleve",
      roi5ans: 24,
      roi10ans: 55,
    },
  },
  {
    id: "p12",
    title: "Local commercial au centre de Porto",
    description: "Espace commercial de 150m² sur deux niveaux en plein centre de Porto. Idéal pour restaurant, boutique ou galerie. Rénové avec goût, prêt à l'emploi.",
    type: "commercial",
    transactionType: "location-lt",
    price: 2800,
    currency: "EUR",
    location: { address: "Rua das Flores 78", city: "Porto", country: "Portugal", lat: 41.1452, lng: -8.613 },
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop"],
    videos: [],
    bedrooms: 0,
    bathrooms: 2,
    area: 150,
    floor: 0,
    equipment: ["Vitrine", "Cave", "Cuisine professionnelle", "Climatisation", "Alarme", "Accessible PMR"],
    host: users[12],
    rating: 4.5,
    reviewCount: 8,
    views: 1230,
    createdAt: "2025-02-10",
    status: "active",
    featured: false,
    paidOptions: [],
  },
  {
    id: "p13",
    title: "Villa sur les hauteurs de Nice",
    description: "Superbe villa provençale de 250m² avec piscine et jardin paysager sur les collines de Nice. Vue mer panoramique, calme absolu, à 10 minutes du centre.",
    type: "villa",
    transactionType: "vente",
    price: 2200000,
    currency: "EUR",
    location: { address: "Chemin des Collines 22", city: "Nice", country: "France", lat: 43.7102, lng: 7.262 },
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a6?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop"],
    videos: ["/videos/property-tour-2.mp4"],
    bedrooms: 5,
    bathrooms: 3,
    area: 250,
    equipment: ["Piscine", "Jardin", "Vue mer", "Garage double", "Cave à vin", "Cuisine d'été", "Alarme"],
    host: users[10],
    rating: 4.8,
    reviewCount: 5,
    views: 6780,
    createdAt: "2025-01-10",
    status: "active",
    featured: true,
    paidOptions: [],
    analytics: {
      rendementBrut: 5.2,
      rendementNet: 3.8,
      prixM2: Math.round(2200000 / 250),
      dpe: "B",
      etatGeneral: "Excellent",
      anneeConstruction: 1998,
      potentielPlusValue: "Eleve",
      roi5ans: 28,
      roi10ans: 65,
    },
  },
  {
    id: "p14",
    title: "Appartement cosy à Montreux",
    description: "Charmant 3 pièces rénové au cœur de Montreux, à deux pas du lac et de la promenade fleurie. Idéal pour le Festival de Jazz ou un séjour détente.",
    type: "appartement",
    transactionType: "location-ct",
    price: 1800,
    currency: "CHF",
    pricePerNight: 160,
    location: { address: "Grand-Rue 30", city: "Montreux", country: "Suisse", lat: 46.4312, lng: 6.9107 },
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop"],
    videos: [],
    bedrooms: 2,
    bathrooms: 1,
    area: 70,
    floor: 3,
    equipment: ["WiFi", "Balcon vue lac", "Cuisine équipée", "Lave-linge", "TV", "Proche gare"],
    host: users[15],
    rating: 4.7,
    reviewCount: 34,
    views: 1560,
    createdAt: "2025-02-05",
    status: "active",
    featured: false,
    paidOptions: paidOptionsSets.standard,
  },
];

// ─── Social Posts ────────────────────────────────────────

export const socialPosts: SocialPost[] = [
  {
    id: "sp1",
    author: currentUser,
    content: "Nouvelle propriété en ligne ! Magnifique vue sur le lac de Neuchâtel depuis cet appartement entièrement rénové. Réservations ouvertes pour la saison d'été.",
    media: [{ type: "image", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop" }, { type: "image", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop" }],
    likes: 87,
    comments: [
      { id: "c1", author: users[1], content: "Superbe ! La vue est incroyable", createdAt: "2026-03-20T14:30:00Z", likes: 12 },
      { id: "c2", author: users[5], content: "Je connais des clients intéressés, je te contacte !", createdAt: "2026-03-20T15:00:00Z", likes: 5 },
    ],
    shares: 14,
    saves: 23,
    createdAt: "2026-03-20T12:00:00Z",
    type: "post",
    property: properties[0],
    hashtags: ["#immobilier", "#neuchatel", "#vueSurLeLac", "#locationSuisse"],
  },
  {
    id: "sp2",
    author: users[3],
    content: "Découvrez notre villa de luxe à la Palmeraie de Marrakech. Un havre de paix au milieu des palmiers, avec piscine privée et personnel dédié.",
    media: [{ type: "image", url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop" }, { type: "image", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop" }, { type: "image", url: "https://images.unsplash.com/photo-1548018560-c7196bddcbec?w=800&h=600&fit=crop" }],
    likes: 234,
    comments: [
      { id: "c3", author: users[6], content: "Très bel investissement Amina, bravo !", createdAt: "2026-03-19T10:00:00Z", likes: 8 },
      { id: "c4", author: users[9], content: "Je rêve d'y séjourner un jour !", createdAt: "2026-03-19T11:30:00Z", likes: 15 },
      { id: "c5", author: currentUser, content: "Magnifique propriété, j'aimerais collaborer sur la promotion en Suisse.", createdAt: "2026-03-19T12:00:00Z", likes: 6 },
    ],
    shares: 45,
    saves: 67,
    createdAt: "2026-03-19T09:00:00Z",
    type: "post",
    property: properties[1],
    hashtags: ["#marrakech", "#villa", "#luxe", "#palmeraie", "#vacances"],
  },
  {
    id: "sp3",
    author: users[8],
    content: "Ma nouvelle formation gratuite est en ligne ! « Les bases de l'investissement immobilier en Suisse » — 6 modules pour comprendre le marché, le financement et la fiscalité.",
    media: [{ type: "image", url: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&h=600&fit=crop" }],
    likes: 456,
    comments: [
      { id: "c6", author: users[9], content: "Merci Thomas ! Exactement ce qu'il me fallait", createdAt: "2026-03-18T09:00:00Z", likes: 34 },
      { id: "c7", author: users[1], content: "Formation très complète, je recommande vivement !", createdAt: "2026-03-18T10:30:00Z", likes: 21 },
    ],
    shares: 89,
    saves: 134,
    createdAt: "2026-03-18T08:00:00Z",
    type: "post",
    hashtags: ["#formation", "#investissement", "#immobilier", "#suisse", "#gratuit"],
  },
  {
    id: "sp4",
    author: users[7],
    content: "Coucher de soleil depuis notre terrasse à Paros. Les Cyclades offrent des moments magiques. Ce terrain est encore disponible pour votre projet de villa de rêve.",
    media: [{ type: "video", url: "/videos/reel-1.mp4" }],
    likes: 567,
    comments: [
      { id: "c8", author: users[14], content: "Spectaculaire ! Je serais intéressé pour un projet.", createdAt: "2026-03-17T20:00:00Z", likes: 9 },
    ],
    shares: 78,
    saves: 145,
    createdAt: "2026-03-17T18:30:00Z",
    type: "reel",
    property: properties[9],
    hashtags: ["#grece", "#paros", "#cyclades", "#sunset", "#terrain", "#vueMer"],
  },
  {
    id: "sp5",
    author: users[2],
    content: "Record battu ! Notre penthouse à Genève a généré plus de 8'000 vues en une semaine. Le marché du luxe genevois reste très dynamique en ce début 2026.",
    media: [{ type: "image", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop" }],
    likes: 189,
    comments: [
      { id: "c9", author: users[10], content: "Le marché genevois ne déçoit jamais !", createdAt: "2026-03-16T14:00:00Z", likes: 7 },
      { id: "c10", author: users[5], content: "Impressionnant Marc ! Des clients potentiels à te présenter.", createdAt: "2026-03-16T15:00:00Z", likes: 4 },
    ],
    shares: 34,
    saves: 56,
    createdAt: "2026-03-16T12:00:00Z",
    type: "post",
    property: properties[2],
    hashtags: ["#geneve", "#luxe", "#penthouse", "#immobilier", "#record"],
  },
  {
    id: "sp6",
    author: users[4],
    content: "Visite guidée de notre appartement dans l'Alfama ! Le charme de Lisbonne, les azulejos, la vue sur le Tage... Tout y est. Disponible dès avril.",
    media: [{ type: "video", url: "/videos/reel-2.mp4" }],
    likes: 312,
    comments: [
      { id: "c11", author: users[1], content: "Lisbonne est sur ma liste ! Combien par nuit ?", createdAt: "2026-03-15T16:00:00Z", likes: 3 },
      { id: "c12", author: users[4], content: "120 EUR/nuit, avec un tarif spécial pour les longs séjours", createdAt: "2026-03-15T16:30:00Z", likes: 5 },
    ],
    shares: 56,
    saves: 89,
    createdAt: "2026-03-15T14:00:00Z",
    type: "reel",
    property: properties[5],
    hashtags: ["#lisbonne", "#alfama", "#portugal", "#airbnb", "#location"],
  },
  {
    id: "sp7",
    author: users[11],
    content: "Notre riad de Fès vient de recevoir le label « Heritage Excellence ». Fière de préserver le patrimoine marocain tout en offrant un confort moderne à nos hôtes.",
    media: [{ type: "image", url: "https://images.unsplash.com/photo-1539437829697-1b4ed5aebd19?w=800&h=600&fit=crop" }, { type: "image", url: "https://images.unsplash.com/photo-1548018560-c7196bddcbec?w=800&h=600&fit=crop" }],
    likes: 198,
    comments: [
      { id: "c13", author: users[3], content: "Félicitations Fatima ! Bien mérité", createdAt: "2026-03-14T11:00:00Z", likes: 12 },
    ],
    shares: 27,
    saves: 43,
    createdAt: "2026-03-14T09:00:00Z",
    type: "post",
    property: properties[8],
    hashtags: ["#fes", "#riad", "#maroc", "#heritage", "#tradition"],
  },
  {
    id: "sp8",
    author: users[14],
    content: "Le marché immobilier de Dubaï continue sa croissance exceptionnelle en 2026. Notre dernière villa à Dubaï Marina illustre parfaitement cette tendance premium.",
    media: [{ type: "image", url: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop" }, { type: "image", url: "https://images.unsplash.com/photo-1582672060674-bc2bd808a8b5?w=800&h=600&fit=crop" }],
    likes: 890,
    comments: [
      { id: "c14", author: users[5], content: "Dubaï reste un marché fascinant pour les investisseurs.", createdAt: "2026-03-13T15:00:00Z", likes: 18 },
      { id: "c15", author: users[2], content: "Des chiffres impressionnants Ahmed !", createdAt: "2026-03-13T16:00:00Z", likes: 11 },
    ],
    shares: 123,
    saves: 234,
    createdAt: "2026-03-13T12:00:00Z",
    type: "post",
    property: properties[6],
    hashtags: ["#dubai", "#luxe", "#investissement", "#realestate", "#marina"],
  },
  {
    id: "sp9",
    author: users[15],
    content: "La saison de ski touche à sa fin mais Verbier reste magique au printemps ! Notre chalet est disponible pour des séjours nature et randonnée dès avril.",
    media: [{ type: "image", url: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&h=600&fit=crop" }],
    likes: 145,
    comments: [],
    shares: 18,
    saves: 32,
    createdAt: "2026-03-12T10:00:00Z",
    type: "post",
    property: properties[3],
    hashtags: ["#verbier", "#chalet", "#suisse", "#montagne", "#printemps"],
  },
  {
    id: "sp10",
    author: users[5],
    content: "3 nouvelles commissions validées ce mois ! Le programme d'apporteurs d'affaires E-Dome fonctionne vraiment. N'hésitez pas à me contacter pour en savoir plus.",
    media: [],
    likes: 98,
    comments: [
      { id: "c16", author: users[9], content: "Comment ça fonctionne exactement ?", createdAt: "2026-03-11T14:00:00Z", likes: 6 },
      { id: "c17", author: users[5], content: "Tu recommandes un bien, et si la transaction se fait, tu touches une commission. Simple et efficace !", createdAt: "2026-03-11T14:30:00Z", likes: 8 },
    ],
    shares: 23,
    saves: 45,
    createdAt: "2026-03-11T12:00:00Z",
    type: "post",
    hashtags: ["#apporteur", "#commission", "#immobilier", "#edome", "#business"],
  },
  {
    id: "sp11",
    author: currentUser,
    content: "Journée portes ouvertes ce samedi à Neuchâtel ! Venez découvrir nos deux appartements disponibles avec vue sur le lac. Café et croissants offerts.",
    media: [{ type: "image", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop" }],
    likes: 67,
    comments: [
      { id: "c18", author: users[9], content: "Je viendrai avec plaisir !", createdAt: "2026-03-10T16:00:00Z", likes: 3 },
    ],
    shares: 12,
    saves: 8,
    createdAt: "2026-03-10T14:00:00Z",
    type: "story",
    hashtags: ["#portesOuvertes", "#neuchatel", "#immobilier", "#visite"],
  },
  {
    id: "sp12",
    author: users[6],
    content: "Visite express de notre penthouse à Genève ! 200m², terrasse panoramique, vue sur le jet d'eau et les Alpes. Le luxe à l'état pur.",
    media: [{ type: "video", url: "/videos/reel-1.mp4" }],
    likes: 423,
    comments: [
      { id: "c19", author: users[2], content: "Mon penthouse préféré du portefeuille !", createdAt: "2026-03-09T11:00:00Z", likes: 14 },
      { id: "c20", author: users[14], content: "Magnifique ! Quel est le prix de vente ?", createdAt: "2026-03-09T12:00:00Z", likes: 7 },
    ],
    shares: 67,
    saves: 112,
    createdAt: "2026-03-09T10:00:00Z",
    type: "reel",
    property: properties[2],
    hashtags: ["#geneve", "#penthouse", "#luxe", "#vueSurLesAlpes", "#realestate"],
  },
  {
    id: "sp13",
    author: users[3],
    content: "Ambiance magique dans notre villa à Marrakech au coucher du soleil. La piscine, les palmiers, le calme... Un vrai paradis pour nos hôtes.",
    media: [{ type: "video", url: "/videos/reel-2.mp4" }],
    likes: 678,
    comments: [
      { id: "c21", author: users[11], content: "Le Maroc a un charme incroyable !", createdAt: "2026-03-08T19:00:00Z", likes: 22 },
    ],
    shares: 89,
    saves: 156,
    createdAt: "2026-03-08T17:30:00Z",
    type: "reel",
    property: properties[1],
    hashtags: ["#marrakech", "#villa", "#sunset", "#piscine", "#luxe"],
  },
];

// ─── Story Users ─────────────────────────────────────────

export const storyUsers = [
  { user: currentUser, hasStory: true, viewed: false },
  { user: users[3], hasStory: true, viewed: false },
  { user: users[7], hasStory: true, viewed: false },
  { user: users[4], hasStory: true, viewed: true },
  { user: users[14], hasStory: true, viewed: false },
  { user: users[11], hasStory: true, viewed: true },
  { user: users[15], hasStory: true, viewed: true },
  { user: users[8], hasStory: true, viewed: false },
  { user: users[2], hasStory: true, viewed: true },
];

// ─── Conversations ───────────────────────────────────────

export const conversations: Conversation[] = [
  {
    id: "conv1",
    participants: [currentUser, users[1]],
    lastMessage: { id: "m1", senderId: "u2", content: "Bonjour ! L'appartement est-il disponible en juillet ?", createdAt: "2026-03-21T09:30:00Z", read: false },
    unreadCount: 2,
    createdAt: "2026-03-20T10:00:00Z",
    updatedAt: "2026-03-21T09:30:00Z",
  },
  {
    id: "conv2",
    participants: [currentUser, users[3]],
    lastMessage: { id: "m2", senderId: "u1", content: "Merci pour les photos, la villa est magnifique !", createdAt: "2026-03-20T18:00:00Z", read: true },
    unreadCount: 0,
    createdAt: "2026-03-18T14:00:00Z",
    updatedAt: "2026-03-20T18:00:00Z",
  },
  {
    id: "conv3",
    participants: [currentUser, users[5]],
    lastMessage: { id: "m3", senderId: "u6", content: "J'ai un client intéressé par votre bien à Neuchâtel, on peut en discuter ?", createdAt: "2026-03-20T15:00:00Z", read: false },
    unreadCount: 1,
    createdAt: "2026-03-19T09:00:00Z",
    updatedAt: "2026-03-20T15:00:00Z",
  },
  {
    id: "conv4",
    participants: [currentUser, users[2]],
    lastMessage: { id: "m4", senderId: "u3", content: "On pourrait organiser une visite du penthouse la semaine prochaine ?", createdAt: "2026-03-19T16:00:00Z", read: true },
    unreadCount: 0,
    createdAt: "2026-03-17T11:00:00Z",
    updatedAt: "2026-03-19T16:00:00Z",
  },
  {
    id: "conv5",
    participants: [currentUser, users[9]],
    lastMessage: { id: "m5", senderId: "u10", content: "Merci pour les conseils ! Je vais étudier les options que vous m'avez proposées.", createdAt: "2026-03-18T20:00:00Z", read: true },
    unreadCount: 0,
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-03-18T20:00:00Z",
  },
  {
    id: "conv6",
    participants: [currentUser, users[8]],
    lastMessage: { id: "m6", senderId: "u9", content: "Votre inscription à la formation « Investissement avancé » est confirmée.", createdAt: "2026-03-17T10:00:00Z", read: true },
    unreadCount: 0,
    createdAt: "2026-03-16T14:00:00Z",
    updatedAt: "2026-03-17T10:00:00Z",
  },
  {
    id: "conv7",
    participants: [currentUser, users[15]],
    lastMessage: { id: "m7", senderId: "u16", content: "Le chalet de Verbier est réservé pour Pâques, mais disponible la semaine suivante.", createdAt: "2026-03-16T12:00:00Z", read: true },
    unreadCount: 0,
    createdAt: "2026-03-14T09:00:00Z",
    updatedAt: "2026-03-16T12:00:00Z",
  },
];

// ─── Reservations ────────────────────────────────────────

export const reservations: Reservation[] = [
  {
    id: "r1",
    property: properties[0],
    guest: users[1],
    checkIn: "2026-04-15",
    checkOut: "2026-04-20",
    guests: 2,
    totalPrice: 925,
    optionsPrice: 185,
    options: [paidOptionsSets.standard[0], { ...paidOptionsSets.standard[1], selected: true }],
    status: "confirmed",
    createdAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "r2",
    property: properties[1],
    guest: users[6],
    checkIn: "2026-05-01",
    checkOut: "2026-05-08",
    guests: 6,
    totalPrice: 3150,
    optionsPrice: 520,
    options: [paidOptionsSets.premium[0], paidOptionsSets.premium[4]],
    status: "confirmed",
    createdAt: "2026-03-18T14:00:00Z",
  },
  {
    id: "r3",
    property: properties[3],
    guest: users[9],
    checkIn: "2026-04-05",
    checkOut: "2026-04-12",
    guests: 4,
    totalPrice: 2660,
    optionsPrice: 345,
    options: [paidOptionsSets.chalet[0], paidOptionsSets.chalet[2]],
    status: "pending",
    createdAt: "2026-03-19T09:00:00Z",
  },
  {
    id: "r4",
    property: properties[5],
    guest: users[1],
    checkIn: "2026-06-10",
    checkOut: "2026-06-17",
    guests: 2,
    totalPrice: 840,
    optionsPrice: 150,
    options: [paidOptionsSets.standard[0]],
    status: "pending",
    createdAt: "2026-03-15T11:00:00Z",
  },
  {
    id: "r5",
    property: properties[0],
    guest: users[5],
    checkIn: "2026-03-01",
    checkOut: "2026-03-05",
    guests: 2,
    totalPrice: 740,
    optionsPrice: 0,
    options: [],
    status: "completed",
    createdAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "r6",
    property: properties[8],
    guest: users[2],
    checkIn: "2026-04-20",
    checkOut: "2026-04-27",
    guests: 4,
    totalPrice: 1120,
    optionsPrice: 200,
    options: [paidOptionsSets.premium[0]],
    status: "confirmed",
    createdAt: "2026-03-10T16:00:00Z",
  },
  {
    id: "r7",
    property: properties[13],
    guest: users[9],
    checkIn: "2026-07-01",
    checkOut: "2026-07-05",
    guests: 2,
    totalPrice: 640,
    optionsPrice: 0,
    options: [],
    status: "pending",
    createdAt: "2026-03-21T08:00:00Z",
  },
  {
    id: "r8",
    property: properties[3],
    guest: users[14],
    checkIn: "2026-02-10",
    checkOut: "2026-02-17",
    guests: 6,
    totalPrice: 2660,
    optionsPrice: 495,
    options: [paidOptionsSets.chalet[0], paidOptionsSets.chalet[1], paidOptionsSets.chalet[3]],
    status: "completed",
    createdAt: "2026-01-25T14:00:00Z",
  },
  {
    id: "r9",
    property: properties[1],
    guest: users[10],
    checkIn: "2026-03-15",
    checkOut: "2026-03-20",
    guests: 4,
    totalPrice: 2250,
    optionsPrice: 0,
    options: [],
    status: "cancelled",
    createdAt: "2026-02-28T10:00:00Z",
  },
  {
    id: "r10",
    property: properties[0],
    guest: users[9],
    checkIn: "2026-08-01",
    checkOut: "2026-08-10",
    guests: 2,
    totalPrice: 1665,
    optionsPrice: 150,
    options: [paidOptionsSets.standard[0]],
    status: "confirmed",
    createdAt: "2026-03-05T12:00:00Z",
  },
];

// ─── Referrals ───────────────────────────────────────────

export const referrals: Referral[] = [
  { id: "ref1", referrer: currentUser, referred: users[1], property: properties[0], commission: 250, status: "paid", createdAt: "2026-02-15", link: "https://edome.ch/r/karim-b1" },
  { id: "ref2", referrer: currentUser, referred: users[9], property: properties[3], commission: 380, status: "validated", createdAt: "2026-03-10", link: "https://edome.ch/r/karim-b2" },
  { id: "ref3", referrer: currentUser, referred: users[6], property: properties[1], commission: 450, status: "pending", createdAt: "2026-03-18", link: "https://edome.ch/r/karim-b3" },
  { id: "ref4", referrer: users[5], referred: users[1], property: properties[0], commission: 250, status: "paid", createdAt: "2026-01-20", link: "https://edome.ch/r/chloe-r1" },
  { id: "ref5", referrer: users[5], referred: users[9], property: properties[5], commission: 180, status: "validated", createdAt: "2026-02-28", link: "https://edome.ch/r/chloe-r2" },
  { id: "ref6", referrer: currentUser, referred: users[10], commission: 500, status: "paid", createdAt: "2026-01-05", link: "https://edome.ch/r/karim-b4" },
  { id: "ref7", referrer: currentUser, referred: users[12], property: properties[11], commission: 320, status: "validated", createdAt: "2026-03-01", link: "https://edome.ch/r/karim-b5" },
  { id: "ref8", referrer: users[5], referred: users[15], property: properties[13], commission: 200, status: "pending", createdAt: "2026-03-15", link: "https://edome.ch/r/chloe-r3" },
  { id: "ref9", referrer: currentUser, referred: users[4], commission: 150, status: "paid", createdAt: "2025-12-10", link: "https://edome.ch/r/karim-b6" },
  { id: "ref10", referrer: currentUser, referred: users[7], property: properties[9], commission: 680, status: "pending", createdAt: "2026-03-20", link: "https://edome.ch/r/karim-b7" },
  { id: "ref11", referrer: users[5], referred: users[11], property: properties[8], commission: 240, status: "paid", createdAt: "2026-02-05", link: "https://edome.ch/r/chloe-r4" },
  { id: "ref12", referrer: currentUser, referred: users[2], property: properties[2], commission: 2500, status: "pending", createdAt: "2026-03-19", link: "https://edome.ch/r/karim-b8" },
  { id: "ref13", referrer: users[5], referred: users[14], property: properties[6], commission: 4200, status: "pending", createdAt: "2026-03-12", link: "https://edome.ch/r/chloe-r5" },
  { id: "ref14", referrer: currentUser, referred: users[11], property: properties[8], commission: 280, status: "validated", createdAt: "2026-02-20", link: "https://edome.ch/r/karim-b9" },
  { id: "ref15", referrer: currentUser, referred: users[8], commission: 120, status: "paid", createdAt: "2025-11-15", link: "https://edome.ch/r/karim-b10" },
];

// ─── Formations ──────────────────────────────────────────

export const formations: Formation[] = [
  {
    id: "f1",
    title: "Les bases de l'investissement immobilier en Suisse",
    description: "Découvrez les fondamentaux de l'investissement immobilier en Suisse : marché, financement, fiscalité et stratégies de rendement.",
    instructor: users[8],
    price: 0,
    currency: "CHF",
    duration: "6h30",
    level: "débutant",
    category: "Investissement",
    thumbnail: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&h=400&fit=crop",
    modules: [
      { id: "m1", title: "Introduction au marché suisse", duration: "45 min", completed: true },
      { id: "m2", title: "Financement et hypothèques", duration: "1h15", completed: true },
      { id: "m3", title: "Fiscalité immobilière", duration: "1h", completed: false },
      { id: "m4", title: "Analyse de rentabilité", duration: "1h", completed: false },
      { id: "m5", title: "Stratégies d'investissement", duration: "1h30", completed: false },
      { id: "m6", title: "Cas pratiques et exercices", duration: "1h", completed: false },
    ],
    rating: 4.9,
    studentsCount: 1245,
    isFree: true,
    previewVideo: "/videos/training.mp4",
  },
  {
    id: "f2",
    title: "Maîtriser la location courte durée",
    description: "Tout savoir pour lancer et optimiser votre activité de location courte durée. De la mise en ligne à la gestion des avis.",
    instructor: users[4],
    price: 199,
    currency: "CHF",
    duration: "8h",
    level: "intermédiaire",
    category: "Location",
    thumbnail: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=600&h=400&fit=crop",
    modules: [
      { id: "m7", title: "Préparer son bien", duration: "1h" },
      { id: "m8", title: "Photos et annonces qui convertissent", duration: "1h30" },
      { id: "m9", title: "Pricing dynamique", duration: "1h" },
      { id: "m10", title: "Accueil et expérience client", duration: "1h30" },
      { id: "m11", title: "Gestion des avis", duration: "1h" },
      { id: "m12", title: "Automatisation et outils", duration: "1h" },
      { id: "m13", title: "Réglementation et fiscalité", duration: "1h" },
    ],
    rating: 4.7,
    studentsCount: 678,
    isFree: false,
  },
  {
    id: "f3",
    title: "Devenir apporteur d'affaires immobilier",
    description: "Apprenez à générer des revenus en recommandant des biens immobiliers. Techniques de prospection, négociation et fidélisation client.",
    instructor: users[5],
    price: 149,
    currency: "CHF",
    duration: "5h",
    level: "débutant",
    category: "Apport d'affaires",
    thumbnail: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop",
    modules: [
      { id: "m14", title: "Le rôle de l'apporteur d'affaires", duration: "45 min" },
      { id: "m15", title: "Construire son réseau", duration: "1h" },
      { id: "m16", title: "Techniques de recommandation", duration: "1h15" },
      { id: "m17", title: "Aspects juridiques et contrats", duration: "1h" },
      { id: "m18", title: "Maximiser ses commissions", duration: "1h" },
    ],
    rating: 4.8,
    studentsCount: 432,
    isFree: false,
  },
  {
    id: "f4",
    title: "Investissement immobilier avancé : multi-pays",
    description: "Stratégies d'investissement immobilier international. Suisse, France, Portugal, Maroc, Dubaï : les opportunités par marché.",
    instructor: users[8],
    price: 399,
    currency: "CHF",
    duration: "12h",
    level: "avancé",
    category: "Investissement",
    thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&h=400&fit=crop",
    modules: [
      { id: "m19", title: "Analyse comparative des marchés", duration: "2h" },
      { id: "m20", title: "Marché suisse avancé", duration: "1h30" },
      { id: "m21", title: "Investir en France", duration: "1h30" },
      { id: "m22", title: "Le marché marocain", duration: "1h30" },
      { id: "m23", title: "Opportunités au Portugal", duration: "1h30" },
      { id: "m24", title: "Dubaï et les Émirats", duration: "1h30" },
      { id: "m25", title: "Fiscalité internationale", duration: "1h30" },
      { id: "m26", title: "Montage de projets multi-pays", duration: "1h" },
    ],
    rating: 4.9,
    studentsCount: 234,
    isFree: false,
  },
  {
    id: "f5",
    title: "Home staging : valoriser son bien pour la vente",
    description: "Techniques professionnelles de home staging pour maximiser le prix de vente de vos biens immobiliers.",
    instructor: users[3],
    price: 89,
    currency: "EUR",
    duration: "4h",
    level: "débutant",
    category: "Vente",
    thumbnail: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&h=400&fit=crop",
    modules: [
      { id: "m27", title: "Principes du home staging", duration: "45 min" },
      { id: "m28", title: "Désencombrer et dépersonnaliser", duration: "45 min" },
      { id: "m29", title: "Mise en lumière et couleurs", duration: "1h" },
      { id: "m30", title: "Photos immobilières professionnelles", duration: "1h30" },
    ],
    rating: 4.6,
    studentsCount: 567,
    isFree: false,
  },
  {
    id: "f6",
    title: "Gestion locative : de A à Z",
    description: "Maîtrisez tous les aspects de la gestion locative : contrats, relations locataires, entretien, comptabilité.",
    instructor: users[12],
    price: 179,
    currency: "EUR",
    duration: "7h",
    level: "intermédiaire",
    category: "Gestion",
    thumbnail: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop",
    modules: [
      { id: "m31", title: "Cadre juridique", duration: "1h30" },
      { id: "m32", title: "Rédiger un bail", duration: "1h" },
      { id: "m33", title: "Sélection des locataires", duration: "1h" },
      { id: "m34", title: "Gestion quotidienne", duration: "1h30" },
      { id: "m35", title: "Comptabilité et fiscalité", duration: "1h" },
      { id: "m36", title: "Travaux et entretien", duration: "1h" },
    ],
    rating: 4.5,
    studentsCount: 345,
    isFree: false,
  },
  {
    id: "f7",
    title: "Le marché du luxe immobilier",
    description: "Comprendre et réussir dans le segment du luxe immobilier. Clientèle, marketing, négociation et closing.",
    instructor: users[14],
    price: 499,
    currency: "CHF",
    duration: "10h",
    level: "avancé",
    category: "Luxe",
    thumbnail: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&h=400&fit=crop",
    modules: [
      { id: "m37", title: "Définir le segment luxe", duration: "1h" },
      { id: "m38", title: "Connaître sa clientèle", duration: "1h30" },
      { id: "m39", title: "Marketing du luxe", duration: "2h" },
      { id: "m40", title: "L'art de la négociation", duration: "2h" },
      { id: "m41", title: "Visites et présentation premium", duration: "1h30" },
      { id: "m42", title: "Closing et suivi client", duration: "2h" },
    ],
    rating: 4.8,
    studentsCount: 123,
    isFree: false,
  },
  {
    id: "f8",
    title: "Rénovation rentable : transformer un bien en pépite",
    description: "Stratégies de rénovation pour maximiser la plus-value. Budget, planning, artisans et suivi de chantier.",
    instructor: users[10],
    price: 249,
    currency: "EUR",
    duration: "9h",
    level: "intermédiaire",
    category: "Rénovation",
    thumbnail: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=600&h=400&fit=crop",
    modules: [
      { id: "m43", title: "Identifier les biens à potentiel", duration: "1h30" },
      { id: "m44", title: "Estimer les travaux", duration: "1h30" },
      { id: "m45", title: "Choisir et gérer les artisans", duration: "1h30" },
      { id: "m46", title: "Suivi de chantier", duration: "1h30" },
      { id: "m47", title: "Optimiser le budget", duration: "1h30" },
      { id: "m48", title: "Cas pratiques de rénovation", duration: "1h30" },
    ],
    rating: 4.7,
    studentsCount: 289,
    isFree: false,
  },
];

// ─── Events ──────────────────────────────────────────────

export const events: Event[] = [
  {
    id: "e1",
    title: "Webinaire : Investir en Suisse en 2026",
    description: "Thomas Müller partage son analyse du marché immobilier suisse et les meilleures opportunités d'investissement pour 2026.",
    date: "2026-04-05",
    time: "18:00",
    type: "webinar",
    speaker: users[8],
    location: "En ligne (Zoom)",
    spots: 200,
    registered: 156,
    price: 0,
    thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&h=400&fit=crop",
  },
  {
    id: "e2",
    title: "Atelier Home Staging — Genève",
    description: "Atelier pratique de 3 heures pour apprendre les techniques de home staging qui font vendre plus vite et plus cher.",
    date: "2026-04-12",
    time: "14:00",
    type: "atelier",
    speaker: users[3],
    location: "Espace Immobilier, Rue du Rhône 14, Genève",
    spots: 25,
    registered: 22,
    price: 120,
    thumbnail: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop",
  },
  {
    id: "e3",
    title: "Séminaire : L'immobilier international",
    description: "Une journée complète de séminaire sur l'investissement immobilier international avec des experts de 5 pays.",
    date: "2026-04-25",
    time: "09:00",
    type: "seminaire",
    speaker: users[8],
    location: "SwissTech Convention Center, Lausanne",
    spots: 150,
    registered: 89,
    price: 350,
    thumbnail: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&h=400&fit=crop",
  },
  {
    id: "e4",
    title: "Live : Visite d'une villa à Marrakech",
    description: "Visite en direct de notre villa de luxe à la Palmeraie de Marrakech. Posez vos questions en temps réel !",
    date: "2026-04-08",
    time: "16:00",
    type: "live",
    speaker: users[3],
    location: "Instagram / YouTube Live",
    spots: 0,
    registered: 430,
    thumbnail: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&h=400&fit=crop",
  },
  {
    id: "e5",
    title: "Webinaire : Fiscalité immobilière pour débutants",
    description: "Comprendre la fiscalité immobilière en Suisse et en France. Impôts, déductions, optimisation légale.",
    date: "2026-05-02",
    time: "19:00",
    type: "webinar",
    speaker: users[8],
    location: "En ligne (Zoom)",
    spots: 300,
    registered: 67,
    price: 0,
    thumbnail: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop",
  },
  {
    id: "e6",
    title: "Atelier networking — Réseau d'apporteurs",
    description: "Soirée networking dédiée aux apporteurs d'affaires. Échangez, créez des partenariats et développez votre réseau.",
    date: "2026-04-18",
    time: "18:30",
    type: "atelier",
    speaker: users[5],
    location: "Le Cercle, Rue de Bourg 3, Lausanne",
    spots: 40,
    registered: 35,
    price: 45,
    thumbnail: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&h=400&fit=crop",
  },
];

// ─── Notifications ───────────────────────────────────────

export const notifications: Notification[] = [
  { id: "n1", type: "reservation", title: "Nouvelle réservation", message: "Sophie Martin a réservé votre appartement à Neuchâtel du 15 au 20 avril.", createdAt: "2026-03-21T09:30:00Z", read: false, link: "/reservations" },
  { id: "n2", type: "payment", title: "Commission validée", message: "Votre commission de CHF 380 pour le parrainage de Yasmine Bouchard a été validée.", createdAt: "2026-03-21T08:00:00Z", read: false, link: "/apporteurs" },
  { id: "n3", type: "message", title: "Nouveau message", message: "Chloé Roux vous a envoyé un message concernant un client intéressé.", createdAt: "2026-03-20T15:00:00Z", read: false, link: "/messages" },
  { id: "n4", type: "like", title: "Votre post a été aimé", message: "87 personnes ont aimé votre publication sur l'appartement de Neuchâtel.", createdAt: "2026-03-20T14:00:00Z", read: false, link: "/feed" },
  { id: "n5", type: "comment", title: "Nouveau commentaire", message: "Chloé Roux a commenté votre publication : « Je connais des clients intéressés »", createdAt: "2026-03-20T13:00:00Z", read: true, link: "/feed" },
  { id: "n6", type: "follow", title: "Nouvel abonné", message: "Yasmine Bouchard a commencé à vous suivre.", createdAt: "2026-03-20T10:00:00Z", read: true, link: "/profil" },
  { id: "n7", type: "reservation", title: "Réservation confirmée", message: "La réservation de Chloé Roux pour le 1-5 mars a été marquée comme terminée.", createdAt: "2026-03-19T16:00:00Z", read: true, link: "/reservations" },
  { id: "n8", type: "system", title: "Vérification KYC", message: "Votre vérification d'identité de niveau 3 a été approuvée. Félicitations !", createdAt: "2026-03-18T10:00:00Z", read: true, link: "/parametres" },
  { id: "n9", type: "referral", title: "Nouveau filleul", message: "Omar Tazi s'est inscrit via votre lien de parrainage.", createdAt: "2026-03-17T12:00:00Z", read: true, link: "/apporteurs" },
  { id: "n10", type: "payment", title: "Paiement reçu", message: "Vous avez reçu CHF 740 pour la réservation de Chloé Roux (1-5 mars).", createdAt: "2026-03-16T09:00:00Z", read: true, link: "/dashboard" },
  { id: "n11", type: "like", title: "Publication populaire", message: "Votre story sur la journée portes ouvertes a été vue 340 fois.", createdAt: "2026-03-15T18:00:00Z", read: true, link: "/feed" },
  { id: "n12", type: "system", title: "Mise à jour plateforme", message: "Nouvelles fonctionnalités disponibles : tableau de bord amélioré et statistiques avancées.", createdAt: "2026-03-14T08:00:00Z", read: true },
  { id: "n13", type: "reservation", title: "Rappel check-in", message: "Le check-in de Sophie Martin est prévu dans 3 semaines (15 avril).", createdAt: "2026-03-13T09:00:00Z", read: true, link: "/reservations" },
  { id: "n14", type: "comment", title: "Réponse à votre commentaire", message: "Amina El Fassi a répondu à votre commentaire sur sa villa de Marrakech.", createdAt: "2026-03-12T14:00:00Z", read: true, link: "/feed" },
  { id: "n15", type: "referral", title: "Commission payée", message: "Votre commission de CHF 250 pour le parrainage de Sophie Martin a été versée.", createdAt: "2026-03-11T10:00:00Z", read: true, link: "/apporteurs" },
];

// ─── Dashboard Stats ─────────────────────────────────────

export const dashboardStats: DashboardStats = {
  totalRevenue: 48750,
  monthlyRevenue: 8450,
  totalBookings: 67,
  occupancyRate: 78,
  averageRating: 4.8,
  totalProperties: 12,
  pendingReservations: 3,
  referralEarnings: 5280,
  totalViews: 24560,
  conversionRate: 4.2,
};

// ─── Transactions ────────────────────────────────────────

export const transactions: Transaction[] = [
  { id: "t1", type: "income", amount: 925, currency: "CHF", description: "Réservation — Appartement Neuchâtel (Sophie Martin)", date: "2026-03-20", status: "completed" },
  { id: "t2", type: "commission", amount: 380, currency: "CHF", description: "Commission apporteur — Chalet Verbier", date: "2026-03-18", status: "pending" },
  { id: "t3", type: "income", amount: 740, currency: "CHF", description: "Réservation — Appartement Neuchâtel (Chloé Roux)", date: "2026-03-05", status: "completed" },
  { id: "t4", type: "commission", amount: 250, currency: "CHF", description: "Commission apporteur — Réservation Sophie Martin", date: "2026-02-15", status: "completed" },
  { id: "t5", type: "expense", amount: 150, currency: "CHF", description: "Frais de ménage — Appartement Neuchâtel", date: "2026-03-05", status: "completed" },
  { id: "t6", type: "income", amount: 1480, currency: "CHF", description: "Réservation — Studio Lausanne (2 semaines)", date: "2026-02-28", status: "completed" },
  { id: "t7", type: "refund", amount: 370, currency: "CHF", description: "Remboursement partiel — Annulation réservation", date: "2026-02-20", status: "completed" },
  { id: "t8", type: "commission", amount: 500, currency: "CHF", description: "Commission apporteur — Inscription Pierre Lecomte", date: "2026-01-05", status: "completed" },
  { id: "t9", type: "income", amount: 2660, currency: "CHF", description: "Réservation — Chalet Verbier (Ahmed Khalil)", date: "2026-02-17", status: "completed" },
  { id: "t10", type: "expense", amount: 320, currency: "CHF", description: "Réparation plomberie — Studio Lausanne", date: "2026-01-15", status: "completed" },
];

// ─── Monthly Revenue ─────────────────────────────────────

export const monthlyRevenue: MonthlyRevenue[] = [
  { month: "Avr 2025", revenue: 3200, bookings: 4 },
  { month: "Mai 2025", revenue: 4500, bookings: 6 },
  { month: "Juin 2025", revenue: 6800, bookings: 9 },
  { month: "Juil 2025", revenue: 8900, bookings: 12 },
  { month: "Août 2025", revenue: 9200, bookings: 14 },
  { month: "Sep 2025", revenue: 5600, bookings: 7 },
  { month: "Oct 2025", revenue: 4100, bookings: 5 },
  { month: "Nov 2025", revenue: 3400, bookings: 4 },
  { month: "Déc 2025", revenue: 7800, bookings: 10 },
  { month: "Jan 2026", revenue: 5200, bookings: 6 },
  { month: "Fév 2026", revenue: 6100, bookings: 8 },
  { month: "Mars 2026", revenue: 8450, bookings: 10 },
];

// ─── Monthly Referral Earnings ───────────────────────────

export const monthlyReferralEarnings: MonthlyReferralEarnings[] = [
  { month: "Oct 2025", earnings: 450, referrals: 2 },
  { month: "Nov 2025", earnings: 270, referrals: 1 },
  { month: "Déc 2025", earnings: 620, referrals: 3 },
  { month: "Jan 2026", earnings: 750, referrals: 2 },
  { month: "Fév 2026", earnings: 930, referrals: 4 },
  { month: "Mars 2026", earnings: 1260, referrals: 5 },
];

// ─── Suggested Users ─────────────────────────────────────

export const suggestedUsers: User[] = [
  users[7],
  users[14],
  users[10],
  users[11],
  users[4],
  users[12],
];

// ─── Trending Hashtags ───────────────────────────────────

export const trendingHashtags = [
  { tag: "#immobilier", posts: 12450 },
  { tag: "#investissement", posts: 8920 },
  { tag: "#suisse", posts: 6780 },
  { tag: "#locationVacances", posts: 5430 },
  { tag: "#marrakech", posts: 4890 },
  { tag: "#luxe", posts: 4320 },
  { tag: "#vueSurLeLac", posts: 3210 },
  { tag: "#apporteur", posts: 2890 },
  { tag: "#dubai", posts: 2560 },
  { tag: "#renovation", posts: 2340 },
];

// ─── Upcoming Appointments ───────────────────────────────

export const upcomingAppointments = [
  { id: "a1", title: "Visite — Appart. Neuchâtel", date: "2026-03-22", time: "10:00", client: "Sophie Martin", type: "visite" as const },
  { id: "a2", title: "Appel — Client investisseur", date: "2026-03-22", time: "14:30", client: "Omar Tazi", type: "appel" as const },
  { id: "a3", title: "Check-in — Studio Lausanne", date: "2026-03-24", time: "15:00", client: "Yasmine Bouchard", type: "checkin" as const },
  { id: "a4", title: "Réunion — Partenariat agence", date: "2026-03-25", time: "11:00", client: "João Silva", type: "reunion" as const },
  { id: "a5", title: "Visite — Penthouse Genève", date: "2026-03-26", time: "09:30", client: "Marc Dupont", type: "visite" as const },
];

// ─── Aliases (mock-prefixed) ────────────────────────────

export const mockProperties = properties;
export const mockPosts = socialPosts;
export const mockStories = storyUsers;
export const mockSuggestions = suggestedUsers;
export const mockTrending = trendingHashtags;
export const mockUsers = users;
export const mockEvents = events;
export const mockEventsExtended = events;
export const mockReservations = reservations;
export const mockTransactions = transactions;
export const mockMonthlyRevenue = monthlyRevenue;
export const mockDashboardStats = dashboardStats;
export const mockReferrals = referrals;
export const mockMonthlyReferralEarnings = monthlyReferralEarnings;
export const mockFormations = formations;

// ─── Reviews ────────────────────────────────────────────

export const mockReviews = [
  { id: 'r1', author: users[1], rating: 5, content: 'Séjour exceptionnel ! Le chalet est magnifique et Karim est un hôte parfait.', date: '2026-02-15' },
  { id: 'r2', author: users[3], rating: 4, content: 'Très bel appartement, bien situé. Petit bémol sur la propreté à l\'arrivée.', date: '2026-01-22' },
  { id: 'r3', author: users[5], rating: 5, content: 'Vue imprenable sur le lac ! Nous reviendrons sans hésiter.', date: '2025-12-10' },
  { id: 'r4', author: users[7], rating: 4, content: 'Bon rapport qualité-prix. La terrasse est un vrai plus.', date: '2025-11-28' },
  { id: 'r5', author: users[2], rating: 5, content: 'Parfait pour les vacances en famille. Tout était prévu.', date: '2025-10-15' },
];

// ─── Activity Feed ──────────────────────────────────────

export const mockActivity = [
  { id: 'a1', icon: 'eye', text: 'Votre bien "Villa Méditerranée" a reçu 24 nouvelles vues', time: 'Il y a 15 min' },
  { id: 'a2', icon: 'heart', text: 'Sophie Martin a ajouté votre chalet en favoris', time: 'Il y a 1h' },
  { id: 'a3', icon: 'message', text: 'Nouveau message de Pierre Durand concernant le Penthouse', time: 'Il y a 2h' },
  { id: 'a4', icon: 'star', text: 'Nouvel avis 5★ sur votre appartement à Neuchâtel', time: 'Il y a 3h' },
  { id: 'a5', icon: 'link', text: 'Votre lien apporteur a généré 3 nouveaux clics', time: 'Il y a 5h' },
  { id: 'a6', icon: 'check', text: 'Commission de CHF 4 500 validée', time: 'Hier' },
];

// ─── Appointments ───────────────────────────────────────

export const mockAppointments = [
  { id: 'rdv1', title: 'Visite Villa Méditerranée', client: 'Jean-Pierre Morel', date: '2026-03-22', time: '10:00' },
  { id: 'rdv2', title: 'Signature compromis', client: 'Émilie Roux', date: '2026-03-23', time: '14:30' },
  { id: 'rdv3', title: 'Estimation bien', client: 'Marc Fontaine', date: '2026-03-25', time: '09:00' },
];

// ─── Favorites ──────────────────────────────────────────

export const favoritePropertyIds = properties.slice(0, 4).map(p => p.id);
export const favoritePostIds = socialPosts.slice(0, 3).map(p => p.id);

// ─── Lookup helpers ─────────────────────────────────────

export function getPropertyById(id: string) { return properties.find(p => p.id === id); }
export function getSimilarProperties(property: typeof properties[0]) { return properties.filter(p => p.id !== property.id && (p.type === property.type || p.location.country === property.location.country)).slice(0, 6); }
export function getReviewsForProperty(_id: string) { return mockReviews; }
export function getFormationById(id: string) { return formations.find(f => f.id === id); }
export function getSimilarFormations(formation: typeof formations[0]) { return formations.filter(f => f.id !== formation.id && f.category === formation.category).slice(0, 4); }

// ─── Payment Reservation ────────────────────────────────

export const mockPaymentReservation = reservations[0];

// ─── Investor Data ──────────────────────────────────────

export const investorKPIs = [
  { label: 'GMV Plateforme', value: 'CHF 2.1M', trend: '+34%' },
  { label: 'Users Actifs', value: '8 240', trend: '+22%' },
  { label: 'Taux Croissance', value: '+28%', trend: '+5%' },
  { label: 'Revenue Mensuel', value: 'CHF 378K', trend: '+18%' },
];
export const investorMetrics = [
  { label: 'Transactions/mois', value: '142' },
  { label: 'Panier moyen', value: 'CHF 14 800' },
  { label: 'LTV', value: 'CHF 1 200' },
  { label: 'CAC', value: 'CHF 95' },
  { label: 'LTV/CAC', value: '12.6x' },
];
export const investorProjections = [
  { year: 'Année 1', users: '10 000', gmv: '2.1M €', revenue: '378K €', margin: '-15%' },
  { year: 'Année 2', users: '50 000', gmv: '15.8M €', revenue: '2.8M €', margin: '12%' },
  { year: 'Année 3', users: '150 000', gmv: '62.4M €', revenue: '11.2M €', margin: '28%' },
];
export const investorMonthlyGrowth = [
  { month: 'Oct', value: 4200 }, { month: 'Nov', value: 5100 }, { month: 'Déc', value: 6800 },
  { month: 'Jan', value: 7200 }, { month: 'Fév', value: 8100 }, { month: 'Mar', value: 8240 },
];
export const investorReports = [
  { id: 'ir1', title: 'Rapport Mensuel — Février 2026', date: '2026-03-01', type: 'Mensuel' },
  { id: 'ir2', title: 'Rapport Mensuel — Janvier 2026', date: '2026-02-01', type: 'Mensuel' },
  { id: 'ir3', title: 'Rapport Trimestriel Q4 2025', date: '2026-01-15', type: 'Trimestriel' },
  { id: 'ir4', title: 'Rapport Annuel 2025', date: '2026-01-01', type: 'Annuel' },
];
